[package]
name = "ton_client_react_native"
version = "0.13.0"
authors = ["Michael Vlasov"]

[lib]
name = "ton_client_react_native"
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2"
jni = { version = "0.12.0", optional = true, default-features = false }
ton_client = { path = "../../client" }

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.12.0", default-features = false }

[profile.release]
lto = true
